//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gf.Frs.OracleGLLoader.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadStatus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoadStatus()
        {
            this.Loads = new HashSet<Load>();
        }
    
        public byte Value { get; set; }
        public string Name { get; set; }
        public byte StatusId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Load> Loads { get; set; }
        public virtual Status Status { get; set; }
    }
}
