//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gf.Frs.OracleGLLoader.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OracleGLEntry
    {
        public long OracleGLEntryId { get; set; }
        public long OracleGLLoadId { get; set; }
        public string UniqueReferenceKey { get; set; }
        public string JournalEntryHeaderNumber { get; set; }
        public string JournalEntryDescription { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public string LineDescription { get; set; }
        public string AccountNumber { get; set; }
        public string AccountDescription { get; set; }
        public string SubAccountDescription { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public string EntrySource { get; set; }
        public Nullable<decimal> EnteredDr { get; set; }
        public Nullable<decimal> EnteredCr { get; set; }
        public Nullable<decimal> AccountedDr { get; set; }
        public Nullable<decimal> AccountedCr { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public string Period { get; set; }
        public Nullable<short> FiscalYearId { get; set; }
        public Nullable<System.DateTime> JECreationDate { get; set; }
        public Nullable<System.DateTime> JELastUpdateDate { get; set; }
        public byte StatusId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual FiscalYear FiscalYear { get; set; }
        public virtual OracleGLLoad OracleGLLoad { get; set; }
        public virtual Status Status { get; set; }
    }
}
